### ISSUE TITLE
Support diagnostics configuration

### ISSUE THREAD

**Issue by vlaaad** [defold/lua-language-server#6]
We want to provide some luacheck configuration at the language server startup time, e.g. known defold globals. Sumneko's diagnostics configuration supports `Lua.diagnostics.globals`. We should respect it in the luacheck.

**Comment by britzl** [comment]
We can add Defold specific globals to the luacheck config while loading .luacheckrc here:

https://github.com/defold/lua-language-server/blob/master/script/core/diagnostics/luacheck.lua#L49-L50
